name: Build

on:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    name: Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
      - name: Run build
        run: |
          npm run build
        continue-on-error: true
      - name: Upload a Build Artifact (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: ./.next
      - name: Upload a Build Artifact (windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: ./.next
      - name: Upload a Build Artifact (macos)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: ./.next
        
