name: Build

on:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    name: Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
      - name: Run build
        run: |
          npm run build
      - name: Compress build files
        run: zip -qq -r ./${{ matrix.is }}.zip .next
        shell: bash
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ matrix.is }}
          path: ./${{ matrix.is }}.zip
        
